apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
    name: istio-operator
    namespace: istio-system
spec:
  profile: empty
  revision: custom
  hub: docker.io/istio
  tag: 1.25.1
  components:
    base:
      enabled: true
    cni:
      enabled: false
    pilot:                  # This is for installing istiod 
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
    egressGateways:
      - name: ilb-gateway
        namespace: istio-system
        enabled: true
  values:
    global:
      proxy:
        autoInject: enabled
