apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-istio
  namespace: istio-system
spec:
  profile: empty  # Start with no default components
  revision: custom  # Enables revision-based injection
  components:
    base:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 3
    cni:
      enabled: true
      k8s:
        hpaSpec:
          minReplicas: 1
          maxReplicas: 3
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
            maxReplicas: 3
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 1
            maxReplicas: 3
  values:
    global:
      istioNamespace: istio-system
      proxy:
        autoInject: "false"
      defaultPodDisruptionBudget:
        enabled: false
