apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-server-vs
  namespace: api-server
spec:
  hosts:
    - {{ .Values.certManager.domain }}
  gateways:
    - istio-system/api-server-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: api-server.api-server.svc.cluster.local
            port:
              number: 8080
