apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrator
  namespace: api-server
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        istio.io/rev: custom  # Replace if not using revisioned injection
    spec:
      restartPolicy: Never
      serviceAccountName: api-server-sa
      containers:
        - name: flyway-migrate
          image: {{ .Values.apiServer.flywayImage }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for Postgres...";
              until nc -z {{ .Values.postgresService.serviceName }}.{{ .Values.namespace.db }}.svc.cluster.local 5432; do sleep 2; done

              echo "Running Flyway migration...";
              flyway migrate -validateMigrationNaming=true

              echo "Calling quitquitquit on sidecar...";
              curl -X POST http://localhost:15000/quitquitquit

              echo "Done"
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://{{ .Values.postgresService.serviceName }}.{{ .Values.namespace.db }}.svc.cluster.local:5432/api
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
