---
# ServiceAccount for the api-server workload
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-sa
  namespace: api-server
automountServiceAccountToken: false  # Disable token auto-mounting
---
# Role defining least-privilege permissions for api-server
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-server-role
  namespace: api-server
rules: []
---
# RoleBinding to associate ServiceAccount with Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-server-rolebinding
  namespace: api-server
subjects:
- kind: ServiceAccount
  name: api-server-sa
  namespace: api-server
roleRef:
  kind: Role
  name: api-server-role
  apiGroup: rbac.authorization.k8s.io