apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.apiServer.serviceAccountName }}
  namespace: {{ .Values.apiServer.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.apiServer.gcpServiceAccountName }}
automountServiceAccountToken: {{ .Values.apiServer.automountToken }}
