apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ENVIRONMENT
              value: "{{ .Values.env.ENVIRONMENT }}"
            - name: BUCKET_NAME
              value: "{{ .Values.env.BUCKET_NAME }}"
            - name: PROJECT_ID
              value: "{{ .Values.env.PROJECT_ID }}"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "{{ .Values.env.GOOGLE_APPLICATION_CREDENTIALS }}"
          volumeMounts:
            - name: gcp-credentials
              mountPath: "/var/secrets/google"
              readOnly: true
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
      imagePullSecrets:
        - name: docker-registry-auth
